### ISSUE TITLE
Need to bump pip package versions

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/api-utils-python#28]
The course-inventory project uses this repository, along with the other packages using `requests`, and the versions are starting to get out of sync. The version of `requests` used here needs to be updated to the latest version, `2.23.0`.

https://github.com/tl-its-umich-edu/api-utils-python/blob/487cceda45a1272e6055c9a3d7f5221146534475/setup.py#L16-L24

https://requests.readthedocs.io/en/master/

Edit: I'm expanding the issue to include other pip package updates. Other projects using `umich-api` are also using `python-dotenv` and `autologging`, and they are getting out of sync. We should just do a full dependency update.

**Comment by ssciolla** [comment]
We need to test the latest versions and extend the ranges.

**Comment by jonespm** [comment]
This is pulling
* requests 2.24.0
* autologging 1.3.2
* python_dotenv 0.14.0

So these all look updated
