### ISSUE TITLE
Update integration tests for scopes with default configuration

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/api-utils-python#30]
@mfldavidson and @lsloan updated the default configuration for a couple of scopes. It would be nice to ensure there are integration tests in `test.py` for these scopes. We'll also need to make sure the test API Directory application for this project has the correct subscriptions.

**Comment by mfldavidson** [comment]
Sorry about that! Working too fast :(

**Comment by ssciolla** [comment]
We should assess whether it makes sense security-wise to really request subscriptions and write integration tests for all missing endpoints. Some of them may require extra approval steps and might be named differently between API Directory instances (prod and test); also, I've heard you don't need subscriptions to use certain endpoints. I identified these scopes in `apis.json` that we don't have subscriptions for; I'll put notes after each regarding my findings.

- [] `mcommunitygroups`: 
- [] `umscheduleofclasses`:
- [] `canvastladmin`:
- [] `itaccounts`:
- [] `placementscores`:

**Comment by jonespm** [comment]
This test is running with the new test subscription
